export const PLAYERS = [
    // Batsmen
    { id: 1, name: "Virat Kohli", country: "India", role: "Batsman", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 2, name: "Rohit Sharma", country: "India", role: "Batsman", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 3, name: "Steve Smith", country: "Australia", role: "Batsman", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 4, name: "Kane Williamson", country: "New Zealand", role: "Batsman", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 5, name: "David Warner", country: "Australia", role: "Batsman", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 6, name: "Shubman Gill", country: "India", role: "Batsman", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 7, name: "Suryakumar Yadav", country: "India", role: "Batsman", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 8, name: "Babar Azam", country: "Pakistan", role: "Batsman", basePrice: 1.5, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 9, name: "Travis Head", country: "Australia", role: "Batsman", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 10, name: "Harry Brook", country: "England", role: "Batsman", basePrice: 1.5, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 11, name: "Faf du Plessis", country: "South Africa", role: "Batsman", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 12, name: "Shreyas Iyer", country: "India", role: "Batsman", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 13, name: "Ruturaj Gaikwad", country: "India", role: "Batsman", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 14, name: "Yashasvi Jaiswal", country: "India", role: "Batsman", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 15, name: "Rinku Singh", country: "India", role: "Batsman", basePrice: 1.5, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },

    // Wicket Keepers
    { id: 16, name: "MS Dhoni", country: "India", role: "Wicket Keeper", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 17, name: "Jos Buttler", country: "England", role: "Wicket Keeper", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 18, name: "Rishabh Pant", country: "India", role: "Wicket Keeper", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 19, name: "Sanju Samson", country: "India", role: "Wicket Keeper", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 20, name: "Quinton de Kock", country: "South Africa", role: "Wicket Keeper", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 21, name: "KL Rahul", country: "India", role: "Wicket Keeper", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 22, name: "Nicholas Pooran", country: "West Indies", role: "Wicket Keeper", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 23, name: "Ishan Kishan", country: "India", role: "Wicket Keeper", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 24, name: "Heinrich Klaasen", country: "South Africa", role: "Wicket Keeper", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 25, name: "Phil Salt", country: "England", role: "Wicket Keeper", basePrice: 1.5, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },

    // All-rounders
    { id: 26, name: "Hardik Pandya", country: "India", role: "All-Rounder", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 27, name: "Ravindra Jadeja", country: "India", role: "All-Rounder", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 28, name: "Ben Stokes", country: "England", role: "All-Rounder", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 29, name: "Glenn Maxwell", country: "Australia", role: "All-Rounder", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 30, name: "Andre Russell", country: "West Indies", role: "All-Rounder", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 31, name: "Cameron Green", country: "Australia", role: "All-Rounder", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 32, name: "Rashid Khan", country: "Afghanistan", role: "All-Rounder", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 33, name: "Axar Patel", country: "India", role: "All-Rounder", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 34, name: "Sunil Narine", country: "West Indies", role: "All-Rounder", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 35, name: "Liam Livingstone", country: "England", role: "All-Rounder", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 36, name: "Sam Curran", country: "England", role: "All-Rounder", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 37, name: "Marcus Stoinis", country: "Australia", role: "All-Rounder", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },

    // Bowlers
    { id: 38, name: "Jasprit Bumrah", country: "India", role: "Bowler", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 39, name: "Pat Cummins", country: "Australia", role: "Bowler", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 40, name: "Mitchell Starc", country: "Australia", role: "Bowler", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 41, name: "Kagiso Rabada", country: "South Africa", role: "Bowler", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 42, name: "Trent Boult", country: "New Zealand", role: "Bowler", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 43, name: "Mohammed Shami", country: "India", role: "Bowler", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 44, name: "Mohammed Siraj", country: "India", role: "Bowler", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 45, name: "Yuzvendra Chahal", country: "India", role: "Bowler", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 46, name: "Kuldeep Yadav", country: "India", role: "Bowler", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 47, name: "Anrich Nortje", country: "South Africa", role: "Bowler", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 48, name: "Jofra Archer", country: "England", role: "Bowler", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 49, name: "Matheesha Pathirana", country: "Sri Lanka", role: "Bowler", basePrice: 1.5, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
    { id: 50, name: "Josh Hazlewood", country: "Australia", role: "Bowler", basePrice: 2.0, currentIPLTeam: "Unsold", status: "Unsold", soldPrice: 0, soldToTeam: null, image: null, set: 1 },
];
